# [[plugins]]
# # repo = 'altercation/vim-colors-solarized'
# # repo = 'frankier/neovim-colors-solarized-truecolor-only'
# # repo = 'lifepillar/vim-solarized8'
# repo = 'iCyMind/NeoSolarized'
# hook_post_source = '''
# set termguicolors
# set background=dark
# colorscheme NeoSolarized
# '''

